### ISSUE TITLE
Legge til CODEOWNERS fil

### ISSUE THREAD

**Issue by MikAoJk** [Mattilsynet/matvaretabellen-deux#1]

**Comment by magnars** [comment]
Hei Joakim! Takk for interessen for repoet. Det var ikke øyeblikkelig åpenbart for meg hvilken fordel vi har av å legge til en CODEOWNERS-fil. Kanskje du vil utdype litt hva du tenker vi oppnår med det?

**Comment by MikAoJk** [comment]
Noen fordeler, CODEOWNERS gjør det mulig å kople team (evt person) og repo maskinelt.
Dette er i seg sjølv ein meget stor fordel, da man kan slippe å forholde seg til enkelt personer men heller team på Github.
Man får også auto varsel på repoet, slik som pull requests, issues, dependabot varsler osv.
Kan også bruke CODEOWNERS, til å styre branch kontroll++.

**Comment by cjohansen** [comment]
Vi får enn så lenge alle varsler vi trenger i kraft av å eie repoet (via et team atpåtil). Branch-kontroll tror jeg ikke blir så aktuelt (ref dagens blogginnlegg: https://parenteser.mattilsynet.io/pull-requests/ 😅).

Jeg skjønner ikke helt hvordan man får noe mer maskinlesbart eierskap enn hva commit-loggen og repo-eierskapet allerede gir?

**Comment by MikAoJk** [comment]
Kan utenforstående se hvilket team som eier repoet?

**Comment by MikAoJk** [comment]
Men dersom derre ikkje ser noe stor gevinst, så er det ikkje så nødvendig. Men ein CONTRIBUTING.md, tror eg er kjekt å ha eller?

**Comment by cjohansen** [comment]
Hei. Det er mulig eksterne ikke kan se team-eierskap, det tenkte jeg ikke på! Vi har en kontakt-seksjon [nederst i README](https://github.com/mattilsynet/matvaretabellen-deux#kontakt), men hvis en CODEOWNERS-fil løser problemer for deg som kontakt-infoen der ikke gjør så kan vi legge den til. Vi ønsker bare å forstå hensikten med det vi legger inn 😊 

Noe informasjon om bidrag burde nok på plass, ja. Takk for engasjementet 👍

**Comment by MikAoJk** [comment]
Bare hyggeligt, da lukker eg denne😊👍
