### ISSUE TITLE
Problem med Calsium feltet av 'Almond based beverage'

### ISSUE THREAD

**Issue by danielphili** [Mattilsynet/matvaretabellen-deux#2]
Hei, 
Tusen takk for deres arbeid med matvaretabellen!
Jeg tror det mangler data på calsium i 'Almond based beverage' food i databasen, eller det oppsto en feil når det ble sist sammenstilt. 
{'sourceId': '10', 'nutrientId': 'Ca'} gir ikke quantity, som skulle være 0.0 hvis det ikker er noe i matvaren, ikke sant? 
For eksempel finner jeg {'sourceId': '400f', 'quantity': 0.1, 'unit': 'mg', 'nutrientId': 'Fe'} for selve 'Almond based beverage'.
Hilsen,

Daniel

**Comment by cjohansen** [comment]
Hei, og takk for interessen! Dette er ikke en teknisk feil, men mangel i dataene. Det stemmer forsåvidt at vi ikke har absolutt alle mineraler for alle matvarer, det kommer litt an på kilden til dataene. Jeg har spilt spørsmålet videre til de som har faglig ansvar for dataene, oppdaterer når jeg vet noe mer 😊

**Comment by cjohansen** [comment]
Som jeg mistenkte så mangler vi rett og slett informasjon om naturlig kalsiuminnhold i dette produktet. Det publiseres nytt datasett hvert år (november-ish), så mitt beste forslag er å prøve igjen etter neste slipp. Det samles inn data fra industri og forskning i disse dager.
